blog/urls.py
from django.conf.urls import url
from . import views
from .views import MainList, PostDetail, AboutMeView

urlpatterns = [
    url(r'^$', MainList.as_view(), name='index'),
    url(r'^about_me$', AboutMeView.as_view(), name='about_me'),
    url(r'^post/(?P<pk>\d+)$', PostDetail.as_view(), name='post_detail'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
    text = models.TextField()
    author = models.CharField(max_length=50, null=True)
    to_post = models.ForeignKey("Post", on_delete=models.CASCADE, db_column="to_post")

blog/forms.py
from django.forms import ModelForm
from django import forms
from blog.models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'author']
        widgets = {
          'text': forms.Textarea(attrs={'rows':1, 'cols':40}),
        }

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db.models import Count
from django.views.generic import View, ListView, DetailView, FormView, TemplateView
from .models import Post, Comment
from .forms import CommentForm
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
# Create your views here.


class MainList(ListView):
    model = Post
    template_name = "blog/index.html"
    paginate_by = 10

    def get_queryset(self):
        queryset = Post.objects.annotate(num_comments=Count('comment'))
        return queryset

class PostDisplay(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDisplay, self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(to_post=self.kwargs.get('pk'))
        context['form'] = CommentForm()
        return context

class PostComment(SingleObjectMixin, FormView):
    template_name = "blog/post_detail.html"
    form_class = CommentForm
    model = Comment

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(PostComment, self).post(self, request, *args, **kwargs)

    def form_valid(self, form):
        text = form.cleaned_data['text']
        author = form.cleaned_data['author']
        post = Post.objects.get(id=self.kwargs['pk'])
        to_post = post
        comment = Comment(text=text, author=author, to_post=to_post)
        comment.save()
        return super(PostComment, self).form_valid(form)

    def get_success_url(self):
        return reverse('post_detail', kwargs={'pk': self.object.pk})

class PostDetail(View):

    def get(self, request, *args, **kwargs):
        view = PostDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = PostComment.as_view()
        return view(request, *args, **kwargs)

    # TODO see django doc and analyze: https://docs.djangoproject.com/en/1.8/topics/class-based-views/mixins/#using-formmixin-with-detailview

class AboutMeView(TemplateView):

    template_name = "blog/about_me.html"

blog/templates/blog/about_me.html
{% extends "blog/index.html" %}

{% block content %}
    <div class="about_me">
    I am a geologist, QA tester, python/django coder. I am really enjoy automation and making things easier.
    </div>
{% endblock %}

blog/templates/blog/footer.html
<div class="footer">
    Made by Andrzej Michalski in django
</div>

blog/templates/blog/index.html
{% load staticfiles %}

<html lang="en">
<head>
    <title>Andrzej Michalski</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
{#    <link rel="stylesheet" href="{% static 'css/blog.css' %}">#}
    <link rel="stylesheet" type="text/css" href="/static/css/blog.css?{% now "U" %}" />
</head>
<body>
    <div class="my_container">
    <header class="page-header">
        <h1>Andrzej Michalski</h1>
    </header>
    <nav class="navbar">
        <span><a href="{% url "index" %}">Blog</a></span>
        <span><a href="">My work</a></span>
        <span><a href="{% url "about_me" %}">About me</a></span>
        <span class="left_navbar">Me on the web</span>
        <span class="my_links">
            <a href="https://www.linkedin.com/in/andrzej-michalski-a43a53152/"><img src="{% static 'img/linkedin.png' %}" style="height: 20px;" alt="linkedin"/></a>
            <a href="https://bitbucket.org/Amfey/"><img class="nav_img" src="{% static 'img/bitbucket.png' %}" alt="bitbucket"/></a>
            <a href="https://www.codewars.com/users/Amfey"><img class="nav_img" src="{% static 'img/codewars.png' %}" alt="codewars"/></a>
        </span>
        <span class="my_cv"><a href="{% static "file/CV_ang.pdf" %}">My CV</a></span>
    </nav>
    <br>
    <div class="content">
        {% block content %}
            {% include 'blog/post_list.html' %}
        {% endblock %}
    </div>
    <footer class="footer">
        Made by Andrzej Michalski in django
    </footer>
    </div>
</body>
</html>

blog/templates/blog/my_links.html
    <h1>Me on the web</h1>

    <p><a href="https://bitbucket.org/Amfey/"> My bitbucket</a></p>

    <p><a href="https://www.linkedin.com/in/andrzej-michalski-a43a53152/"> My LinkedIn</a></p>

    <p><a href="https://www.facebook.com/andrzej.michalski.940"> My facebook</a></p>

    <p><a href="https://www.codewars.com/users/Amfey"> My codewars</a></p>

    <h1>My work</h1>

    <p><a href="https://www.pgi.gov.pl/">PIG-PIB</a></p>

    <p><a href="https://improveo.org/">Improveo</a></p>

    <h2>My CV</h2>

blog/templates/blog/post_detail.html
{% extends "blog/index.html" %}

{% block content %}
    <div class="post_detail">
    <p>published: {{ object.created_date }}</p>
    <h1>{{ post.title }}</h1>
    <p>{{ object.text|linebreaksbr }}</p>
    </div>
    <br>
    <div class="comments">
    <h4>Comments</h4>

    {% for comment in comments %}
        <br>
        <div class="comment">
            <p1>{{ comment.text }}</p1>
            <p>{{ comment.author }}</p>
        </div>
     {% empty %}
        <p1> No comments yet</p1>
    {% endfor %}
    </div>
    <br>
     <h3>Add comment</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
             <input type="submit" value="Submit">
        </form>
    <br>
    <br>
{% endblock %}

blog/templates/blog/post_list.html
{% block content %}
{% for post in object_list %}
    <div>
        <br><br>
        <p>published: {{ post.created_date }}</p>
        <h1><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h1>
        <p>{{ post.text|linebreaksbr }}</p>
        <p><a href="{% url 'post_detail' post.pk %}">Comments ({{ post.num_comments }})</a></p>

{% empty %}
        <h1>No articles yet.</h1>
{% endfor %}
    </div>
    <br>
    <br>
{% endblock %}